### ISSUE TITLE
TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by TreyLawrence** [zihangdai/mos#4] opened 2018-05-01 23:27 UTC
Hello! I'm running into an issue with training the Penn Treeback model:
```python main.py --data data/penn --dropouti 0.4 --dropoutl 0.29 --dropouth 0.225 --seed 28 --batch_size 12 --lr 20.0 --epoch 1000 --nhid 960 --nhidlast 620 --emsize 280 --n_experts 15 --save PTB --single_gpu```

```
Traceback (most recent call last):
  File "main.py", line 260, in <module>
    train()
  File "main.py", line 202, in train
    hidden[s_id] = repackage_hidden(hidden[s_id])
  File "/mos/utils.py", line 12, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/mos/utils.py", line 12, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "/mos/utils.py", line 12, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/mos/utils.py", line 12, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "/mos/utils.py", line 12, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/mos/utils.py", line 12, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "/mos/utils.py", line 12, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/mos/utils.py", line 12, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "/mos/utils.py", line 12, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/mos/utils.py", line 12, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "/mos/utils.py", line 12, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 360, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor
```

**Comment by TreyLawrence** [comment] 2018-05-02 00:11
This is with python3. If I try with python2 I get:
```
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    corpus = data.Corpus(args.data)
  File "/spell/data.py", line 30, in __init__
    self.train = self.tokenize(os.path.join(path, 'train.txt'))
  File "/spell/data.py", line 38, in tokenize
    with open(path, 'r', encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by zihangdai** [comment] 2018-05-02 00:22
What Pytorch version you are using?
`print(torch.__version__)`

**Comment by TreyLawrence** [comment] 2018-05-02 00:45
Thanks for the quick reply! 
I'm using `0.4.0`

**Comment by kimiyoung** [comment] 2018-05-02 02:27
You will need pytorch 0.2.0 to run our code and replicate the results.

**Comment by guillaume-chevalier** [comment] 2018-05-04 04:36
I'd like an update is possible

**Comment by octavian-ganea** [comment] 2018-09-05 13:32
I'm also interested. Is it possible to easily fix the code to work with the latest pytorch version ? Thanks!

**Comment by badripatro** [comment] 2018-10-05 15:15
Hi ,
I am getting same error
-------------------------------------------------------


 File "train/train_GD.py", line 272, in train
    ques_hidden = repackage_hidden(ques_hidden, batch_size)
  File "/home/badri/gpuserver150/data150/workspace_project/visual_dialog/visDial_pytorch_vae_ale/misc/utils.py", line 22, in repackage_hidden
    return tuple(**repackage_hidden**(v, batch_size) for v in h)
  File "/home/badri/gpuserver150/data150/workspace_project/visual_dialog/visDial_pytorch_vae_ale/misc/utils.py", line 22, in <genexpr>
    return tuple(repackage_hidden(v, batch_size) for v in h)
  File "/home/badri/gpuserver150/data150/workspace_project/visual_dialog/visDial_pytorch_vae_ale/misc/utils.py", line 22, in repackage_hidden
    return tuple(repackage_hidden(v, batch_size) for v in h)
  File "/home/badri/gpuserver150/data150/workspace_project/visual_dialog/visDial_pytorch_vae_ale/misc/utils.py", line 22, in <genexpr>
    return tuple(repackage_hidden(v, batch_size) for v in h)
  File "/home/badri/gpuserver150/data150/workspace_project/visual_dialog/visDial_pytorch_vae_ale/misc/utils.py", line 22, in repackage_hidden
    return tuple(repackage_hidden(v, batch_size) for v in h)
  File "/home/badri/gpuserver150/data150/workspace_project/visual_dialog/visDial_pytorch_vae_ale/misc/utils.py", line 22, in <genexpr>
    return tuple(repackage_hidden(v, batch_size) for v in h)
  File "/home/badri/gpuserver150/data150/workspace_project/visual_dialog/visDial_pytorch_vae_ale/misc/utils.py", line 22, in repackage_hidden
    return tuple(repackage_hidden(v, batch_size) for v in h)
  File "/home/badri/gpuserver150/data150/workspace_project/visual_dialog/visDial_pytorch_vae_ale/misc/utils.py", line 22, in <genexpr>
    return tuple(repackage_hidden(v, batch_size) for v in h)
  File "/home/badri/gpuserver150/data150/workspace_project/visual_dialog/visDial_pytorch_vae_ale/misc/utils.py", line 22, in repackage_hidden
    return tuple(repackage_hidden(v, batch_size) for v in h)
  File "/home/badri/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 381, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f16c0be6ac8>>

---------------------------------------------------------

I need in pytorch version 0.4 to run my code.

**Comment by huu4ontocord** [comment] 2018-10-13 15:24
Has this been fixed?  I think the problem is the function never finds a Variable and it recurses all the way to the single element in a tensor.

**Comment by huu4ontocord** [comment] 2018-10-13 16:20
I think the answer is to use isinstanceof instead of type in repackage_hidden

    if isinstance(h, Variable):

**Comment by kimiyoung** [comment] 2018-10-13 18:10
I think this should be fairly easy to fix, but sorry that we don't have time for this at this point. You are welcome to initiate a pull request.

**Comment by kimiyoung** [comment] 2018-10-22 17:20
resolved by #9

**Closed as completed by kimiyoung** 2018-10-22 17:20 UTC

**Comment by Harrite77** [comment] 2019-03-21 09:44
Execuse me, I got the same error today, could you tell me any method to solve it? thank you!

**Comment by c04s84** [comment] 2019-04-01 08:03
> if isinstance(h, Variable):

this solved my problem. thank you so much!
